### PR TITLE
Added sure

### PR DESCRIPTION
**Pull request by ichux**
I refactored a line and it was making the tests break, probably. So, I added it back based on https://github.com/spulec/uncurl/pull/11#issuecomment-376172211

### CODE REVIEW

**Comment by spulec** [comment]
Awesome. Thanks for your contribution!

**Comment by ichux** [comment]
Thanks for allowing me the time to do those changes. I work with mitmproxy. And this library has been extremely helpful.

I have altered it to taste, however, for postman. It's still rudimentary for now. Maybe when I'm done I will show you and let you decide if such is needed.

**Comment by spulec** [comment]
Yeah, I've done some work with mitmproxy in the past.

Definitely let me know what you come up with and we can see if it makes sense to add to uncurl.

Thanks again for your contributions!

**Comment by ichux** [comment]
Cool. I will. Thanks so much.

**Pull request merged**
